version: '3.9'

services:
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_DB: gestion_de_stage
      POSTGRES_USER: root
      POSTGRES_PASSWORD: F@KO1ALK
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d gestion_de_stage"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: aurellefoko/gestion_stagiaire:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/gestion_de_stage
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: F@KO1ALK
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    ports:
      - "8185:8185"
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@stage.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: