openapi: 3.0.3
info:
  title:  Internship Management REST API
  description: REST API endpoints for internship management
  version: v1
servers:
  - url: http://localhost:8080/api/internship-management/v1
tags:
  - name: User
    description: Operations related to user management and functionality.

paths:
  /auth/login:
    post:
      tags:
        - User
      summary: authenticate user
      description: get access token after identified the user
      operationId: login
      requestBody:
        description: data that contain the credentials of the user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequestDTO'
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenDTO'
  /auth/register:
    post:
      tags:
        - User
      summary: Create a new user
      description: Create a new user
      operationId: createUser
      requestBody:
        description: data that need to be use for create User
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequestDTO'
      responses:
        200:
          description: successful operation
  /user:
    get:
      tags:
        - User
      summary: get current User
      description: get current User
      operationId: getCurrentUser
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
components:
  schemas:
    PhoneNumberDTO:
      type: object
      properties:
        number:
          type: string
          example: 677889900
        countryCode:
          type: string
          example: 237
    AuthRequestDTO:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    TokenDTO:
      type: object
      properties:
        value:
          type: string
    RegistrationRequestDTO:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        dateOfBirth:
          type: string
          format: date
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumberDTO'
    RegistrationDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: created user ID
        accessToken:
          $ref: '#/components/schemas/TokenDTO'
    UserDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Identifier of user
        email:
          type: string
        firstname:
          type: string
          description: user firstname
        lastname:
          type: string
          description: user lastname
        username:
          type: string

