spring:
  application:
    name: gestion-de-stagiares

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

  mail:
    host: smtp.gmail.com
    port: 587
    username: aurellefoko117@gmail.com
    password: xxlnsgbsczepphbe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /api/internship-management/v1
  port: 8185
