spring:
  application:
    name: gestion-de-stagiares

  datasource:
    url: "jdbc:postgresql://localhost:5435/gestion-de-stage"
    username: "root"
    password: "F@KO1ALK"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: "create-drop"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
server:
  servlet:
    context-path: /api/internship-management/v1
  port: 8185